version: "3.11"

services:
  html2pdf:
    build: .
    container_name: html2pdf_mcp
    ports:
      - "8000:8000"   # FastAPI app
      - "9000:9000"   # MCP server
    volumes:
      - .:/app        # Mount code for live reload (optional in dev)
    environment:
      - PYTHONUNBUFFERED=1
